name: Build rapidocr test gui
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.9.0 torchvision==0.24.0 --index-url https://download.pytorch.org/whl/cu128
          pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: rapidocr_test_gui.py
          mode: standalone
          include-data-dir: 'savedir=savedir'
          mingw64: true
          enable-plugins: pyside6
          company-name: "Liiesl"
          product-name: "RTG"
          file-description: "test gui for rapidocr"
          file-version: "0.1.0"
          product-version: "0.1.0"

      - name: Zip Minimal Build Output
        run: |
          cd build/rapidocr_test_gui.dist
          7z a -t7z -mx=9 -mf=off ..\..\main-app-build.7z *
          cd ..\..
        shell: pwsh

      - name: Upload Main Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-app-build
          path: main-app-build.7z

    